"""Shared contracts for the admissions consultation system."""

from .contracts import (
    AnswerPayload,
    AnswerStatus,
    ApplicationStage,
    AudienceType,
    CaseCategory,
    CaseProfile,
    ClassificationResult,
    ConversationMode,
    EscalationDecision,
    EscalationReason,
    EvidenceHit,
    FreshnessStatus,
    MessageAttachment,
    NormalizedActor,
    NormalizedMessage,
    PropertyLockStatus,
    RoutingPolicy,
    SpecialProgram,
    UnitAccountStatus,
)

__all__ = [
    "AnswerPayload",
    "AnswerStatus",
    "ApplicationStage",
    "AudienceType",
    "CaseCategory",
    "CaseProfile",
    "ClassificationResult",
    "ConversationMode",
    "EscalationDecision",
    "EscalationReason",
    "EvidenceHit",
    "FreshnessStatus",
    "MessageAttachment",
    "NormalizedActor",
    "NormalizedMessage",
    "PropertyLockStatus",
    "RoutingPolicy",
    "SpecialProgram",
    "UnitAccountStatus",
]
